MAUVE='#9777A6'
RED='#C26D78'
PEACH='#C49A5A'
YELLOW='#D1A85A'
SLATE='#78839A'

SAPPHIRE='#7187A8'


G01='#1C1B20'
G03='#242229'
G04='#2D2A33'
G05='#3A3540'
G07='#716B78'
TC1='#E3DFE6'

FG="$TC1"
BG='#1C1C1C'
INACTIVE_BG='#161616'
BG='#161616'
INACTIVE_BG='#1B1B1B'

set -g window-style "bg=$INACTIVE_BG"
set -g window-active-style "bg=$BG"

set -g pane-border-style "fg=$G05,bg=$BG"
set -g pane-active-border-style "fg=$MAUVE,bg=$BG"

set -g status-fg "$FG"
set -g status-bg "$BG"

# prefix indicator
prefix_color="#{?client_prefix,#[fg=$MAUVE],#[fg=$G03]}#[bg=$BG]"
prefix_bg="#{?client_prefix,#[bg=$MAUVE],#[bg=$G03]}"
prefix_fg="#{?client_prefix,#[fg=$G01],#[fg=$TC1]}$prefix_bg"
prefix_status="$prefix_color$prefix_fg #{prefix}"

# copy mode indicator
mode_color="#{?pane_in_mode,#[fg=$PEACH],#[fg=$G04]}$prefix_bg"
mode_bg="#{?pane_in_mode,#[bg=$PEACH],#[bg=$G04]}"
mode_fg="#{?pane_in_mode,#[fg=$G01],#[fg=$TC1]}$mode_bg"
mode_status="$mode_color$mode_fg #{?pane_in_mode,COPY,NORMAL}"

zoom_status="#{?window_zoomed_flag,#[fg=$G01#,bg=$YELLOW] ZOOM ,}"
sync_status="#{?pane_synchronized,#[fg=$G01#,bg=$RED] SYNC ,}"
datetime_status="#[fg=$TC1,bg=$G05] %Y-%m-%d %H:%M"

set -g status-left-length 20
set -g status-left "#[fg=$INACTIVE_BG,bg=$SAPPHIRE]  #{b:session_name} #[fg=$FG,bg=$BG]"

set -g status-right-length 150
set -g status-right "$zoom_status$sync_status$prefix_status $mode_status $datetime_status "

set -g status-justify left
set -g window-status-separator ""
set -g window-status-format " #I:#W#F "
set -g window-status-current-format " #I:#W#F "
set -g window-status-current-style "fg=$G01,bg=$SAPPHIRE,bold"
set -g window-status-activity-style "fg=$YELLOW,bg=$G03"
set -g window-status-bell-style "fg=$RED,bg=$G03,bold"

set -g display-panes-colour "$G07"
set -g display-panes-active-colour "$MAUVE"
set -g clock-mode-colour "$MAUVE"
set -g clock-mode-style 24

set -g message-style "fg=$G01,bg=$YELLOW,bold"
set -g message-command-style "fg=$TC1,bg=$G04"
set -g mode-style "fg=$G01,bg=$MAUVE"

set -g default-terminal "tmux-256color"
set -as terminal-features ",alacritty*:RGB,tmux-256color:RGB,xterm-256color:RGB"

set -g default-command "${SHELL}"
set -g activity-action any
set -g base-index 0
set -g pane-base-index 0
set -g bell-action any
set -g history-limit 50000
set -g mouse on
set -g prefix C-b
set -g renumber-windows on
set -g status-interval 5
set -g status-position bottom
set -g mode-keys vi
set -g status-keys vi
set -g visual-activity on
set -g visual-bell on
set -g word-separators "!\"#$%&'()*+,-./:;<=>?@[\\]^\`{|}~"

# vi-style pane nav
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind ! break-pane -a
bind R source-file ~/.tmux.conf \; display " Config Reloaded!"
bind M-c attach-session -c "#{pane_current_path}" \; display " Session attached"
bind S set-window-option synchronize-panes \; display "Sync toggled"

unbind-key x # stupid asking me if I want to kill a pane

bind-key x kill-pane
bind-key X kill-window

set -g @ssh-split-h-key "|"
set -g @ssh-split-v-key "_"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'pschmitt/tmux-ssh-split'

set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

if-shell '[ -x "$HOME/.tmux/plugins/tpm/tpm" ]' 'run "$HOME/.tmux/plugins/tpm/tpm"'
