set -g default-terminal "tmux-256color"
set -as terminal-features ",alacritty*:RGB,tmux-256color:RGB,xterm-256color:RGB"

set-option -g default-command "${SHELL}"
set-option -g activity-action any
set-option -g assume-paste-time 1
set-option -g base-index 0
set-option -g bell-action any
set-option -g default-size 80x24
set-option -g destroy-unattached off
set-option -g detach-on-destroy on
setw -g display-panes-active-colour red
setw -g display-panes-colour blue
set-option -g display-panes-time 1000
set-option -g display-time 750
set-option -g history-limit 50000
set-option -g key-table root
set-option -g lock-after-time 0
set-option -g lock-command "lock -np"
set-option -g message-command-style bg=black,fg=yellow
set-option -g message-style bg=yellow,fg=black
set-option -g mouse off
set-option -g prefix C-b
set-option -g renumber-windows on
set-option -g repeat-time 500
set-option -g set-titles off
set-option -g set-titles-string "#S:#I:#W - \"#T\" #{session_alerts}"
set-option -g silence-action none
set-option -g status on
set-option -g status-bg default
set-option -g status-fg default
set-option -g status-interval 15
set-option -g status-justify left
set-option -g mode-keys vi
set-option -g status-keys vi
set-option -g status-left "[#{session_name}] "
set-option -g status-left-length 10
set-option -g status-left-style default
set-option -g status-position bottom
set-option -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}\"#{=21:pane_title}\" %H:%M %d-%b-%y"
set-option -g status-right-length 40
set-option -g status-right-style default
set-option -g status-style bg=green,fg=black
set-option -g update-environment "DISPLAY KRB5CCNAME SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY"
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-option -g word-separators "!\"#$%&'()*+,-./:;<=>?@[\\]^`{|}~"

# Vi-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind | split-window -h
bind _ split-window -v
unbind '"'
unbind %

bind R source-file ~/.tmux.conf \; display "Config Reloaded!"
bind M-c attach-session -c "#{pane_current_path}" \; display "Session attached"

unbind-key x # stupid asking me if I want to kill a pane
bind-key x kill-pane
bind-key X kill-window

set -g @plugin 'tmux-plugins/tmux-resurrect'

if-shell '[ -x "$HOME/.tmux/plugins/tpm/tpm" ]' 'run "$HOME/.tmux/plugins/tpm/tpm"'
